"""Global const list of images"""
image_options = [
                    {
                        'name':'Brazil',
                        'link':'static/imgs/brazil.png'
                    },
                    {
                        'name':'China',
                        'link':'static/imgs/china.png'
                    }, 
                    {
                        'name':'Czech Republic',
                        'link':'static/imgs/czech-republic.png'
                    }, 
                    {
                        'name':'Germany',  
                        'link':'static/imgs/germany.png'
                    }, 
                    {
                        'name':'Japan',  
                        'link':'static/imgs/japan.png'
                    }, 
                    {
                        'name':'Netherlands',  
                        'link':'static/imgs/netherlands.png'
                    }, 
                    {
                        'name':'South-africa', 
                        'link':'static/imgs/south-africa.png'
                    }, 
                    {
                        'name':'South-korea', 
                        'link':'static/imgs/south-korea.png'
                    }, 
                    {
                        'name':'USA', 
                        'link':'static/imgs/usa.png'
                    }
                ]